# config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "assets/images"
publish_mode: editorial_workflow
site_url: "http://erc.cuhk.edu.hk/"
collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts/"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "/{{slug}}"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "single" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - label: "header"
        name: "header"
        widget: "list"
        required: false
        fields:
          - {
              label: "overlay_image",
              name: "overlay_image",
              widget: "image",
              allow_multiple: false,
              required: false,
            }
          - {
              label: "overlay_filter",
              name: "overlay_filter",
              widget: "number",
              valueType: "float",
              min: 0,
              max: 1,
              step: 0.01,
              default: 0.5,
            }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "tags",
          name: "tags",
          widget: "list",
          required: false,
          default: ["others"]
        }
      - {
          label: "categories",
          name: "categories",
          widget: "list",
          required: false,
          default: ["ASC"]
        }
      - { label: "execept", name: "execept", widget: "string", required: false }
      - { label: "tagline", name: "tagline", widget: "string", required: false }
      - label: "sidebar"
        name: "sidebar"
        widget: "list"
        required: false
        fields:
          - {
              label: "image",
              name: "image",
              widget: "image",
              allow_mulitple: false,
              required: false,
            }